name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle Cache
      uses: gradle/gradle-build-action@v3
      with:
         gradle-home-cache-cleanup: true

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%YYYY-%mm-%dd-HH-mm-ss')"

    - name: Bump Version Code
      uses: chkfung/android-version-actions@v1.2.3
      with:
        gradlePath: app/build.gradle.kts
        versionCode: ${{ github.run_number }}
        versionName: 1.0.0
               
    - name: gradle build
      run: chmod +x gradlew

    - name: Bundle 'release' with Gradle
      run: ./gradlew bundleRelease assembleRelease

#this build tools part is from https://github.com/r0adkll/sign-android-release/issues/84
    - name: Setup build tool version variable
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION
   
    - name: Sign AAB
      id: sign_aab
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
        alias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
  
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: aab
        path: ${{steps.sign_aab.outputs.signedReleaseFile}}
     
    - name: Sign APK
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
        alias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
       
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.outputs.signedReleaseFile}}


    - run: echo "Build status report=${{ job.status }}."
