name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Get current date
      id: date
      run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
        
    - name: Bump Version Code
      uses: chkfung/android-version-actions@v1.2.3
      with:
        gradlePath: app/build.gradle.kts
        versionCode: ${{ github.run_number }}
        versionName: ${{ env.NOW }}
               
    - name: gradle build
      run: chmod +x gradlew

    - name: Bundle 'release' with Gradle
      run: ./gradlew bundleRelease assembleRelease

#this build tools part is from https://github.com/r0adkll/sign-android-release/issues/84
    - name: Setup build tool version variable
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION
   
    - name: Sign AAB
      id: sign_aab
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
        alias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
  
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: aab
        path: ${{steps.sign_aab.outputs.signedReleaseFile}}
     
    - name: Sign APK
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
        alias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
       
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.outputs.signedReleaseFile}}

  deploy:
    name: Deploy aab to playstore
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download app bundle from artifact
        uses: actions/download-artifact@v4
        with:
          name: app-bundle
      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: '${{ secrets.SERVICE_ACCOUNT_JSON }}'
          packageName: at.tamber.yokolog
          releaseFiles: '${{ github.workspace }}/app-release.aab'
          track: production
